const Constants = {
  EXPO_IP: "192.168.2.15", // TODO: For development purposes this needs to be updated to match the IP of expo go after each update
  SERVER_URL: "http://localhost",
  SERVER_PORT: "4000",
  EXPO_PORT: "8081",
  SPOTIFY_URL: "https://open.spotify.com",
  SPOTIFY_API_URL: "https://api.spotify.com/v1",
  APP_SCHEME: "exp",
  SCOPE: [
    "user-read-currently-playing",
    "user-read-recently-played",
    "user-read-playback-state",
    "user-top-read",
    "user-modify-playback-state",
    "streaming",
    "user-read-email",
    "user-read-private",
  ],
  REDIRECT_URI: "exp://127.0.0.1:19000/",
  DEVICE_ID_LENGTH: 40,
  DEFAULT_PROFILE_IMAGE: "http://www.gravatar.com/avatar/?d=mp",
  SPOTIFY_GREEN: "#1DB954",
  SPOTIFY_PURPLE: "#B026FF",
  SPOTIFY_BLACK: "#191414",
  HEADER_STYLES: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "13%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(10, 10, 10, 0.5)",
  },
  INSTRUCTION_TEXT_STYLES: {
    color: "#BBB",
    fontSize: 22,
    marginHorizontal: 60,
    marginTop: 220,
    marginBottom: 10,
  },
  TEXT_INPUT_STYLES: {
    marginTop: 10,
    padding: 10,
    width: 300,
    fontSize: 24,
    color: "#fff",
    backgroundColor: "#101010",
    borderStartColor: "#B026FF",
    borderStartWidth: 1,
    borderBottomColor: "#B026FF",
    borderBottomWidth: 2,
    borderBottomEndRadius: 100,
  },
};

export default Constants;
